# lje-util
# Generates the annotations for LJE by parsing the JSON files

# Type-checking in python is very irritating
# type: ignore

import os
import json
import typing
import urllib.request
import zipfile
import shutil

JSONInstance = typing.Union[dict[str, "JSONInstance"], list["JSONInstance"], str, int, float, bool]

namespaces = []
output = []

def getformatteddescription(description):
    if (not (type(description) is list)):
        description = description.split("\n")

    descriptionoutput = []
    for line in description:
        descriptionoutput.append("--- " + line)
    return "\n".join(descriptionoutput)

def parse(data: dict[str, JSONInstance], prefix: str):
    if (not ("namespace" in data)):
        return

    namespace = data["namespace"]
    constants = data["constants"] if ("constants" in data) else []
    functions = data["functions"] if ("functions" in data) else []
    classes = data["classes"] if ("classes" in data) else []

    isbase = namespace == "base"

    if (isbase):
        fprefix = prefix
        cprefix = ""
    else:
        fprefix = prefix + namespace + "."
        cprefix = fprefix
        namespaces.append(f"{getformatteddescription(data['description'])}\n{prefix}{namespace} = {{}}")

    for ljeclass in classes:
        name = ljeclass["name"]
        line = []
        line.append("--- " + ljeclass["description"])
        line.append("--- @class " + name)
        for method in ljeclass["methods"]:
            params = [f"self: {name}"]
            for param in method["params"]:
                pname: str = param['name']
                ptype: str = param['type']
                if ("..." in pname):
                    params.append(f"{pname}: {ptype.strip("...")}")
                else:
                    params.append(f"{pname}: {ptype}")

            returns = []
            for ret in method["returns"]:
                returns.append(ret['type'])

            if (len(returns) == 0):
                returns.append("nil")

            funcdef = f"fun({', '.join(params)}): {', '.join(returns)}"

            line.append(f"--- @field {method['name']} {funcdef} {method['description']}")
        output.append("\n".join(line))
    
    for const in constants:
        if (isbase and not const['name'].startswith("lje.")):
            continue # Don't add polyfills and stuff like that

        line = []
        line.append(getformatteddescription(const['description']))
        line.append(f"--- @type {const['type']}")
        line.append(f"{cprefix}{const['name']} = nil")
        output.append("\n".join(line))
    
    for function in functions:
        line = []
        line.append(getformatteddescription(function['description']))

        params = []
        for param in function["params"]:
            pname: str = param['name']
            ptype: str = param['type']
            if ("..." in pname):
                ptype = ptype.strip("...")
            line.append(f"--- @param {pname} {ptype}{'?' if (('optional' in param) and (param['optional'])) else ''} {param['description']}")
            params.append(pname)
        
        i = 1
        for ret in function['returns']:
            string: str = ret['type']
            if (string.find("...") != -1):
                string = "..."
            line.append(f"--- @return {string}{'?' if (('optional' in ret) and (ret['optional'])) else ''} R{i} {ret['description']}")
            i = i + 1
        
        line.append(f"function {fprefix}{function['name']}({', '.join(params)}) end --- @diagnostic disable-line")
        output.append("\n".join(line))

def loadrepository(url, prefix):
    pathout = "git-repo-annotations"
    pathin = pathout + "-zip"
    urllib.request.urlretrieve(url, pathin)
    with zipfile.ZipFile(pathin, "r") as zip:
        zip.extractall(pathout)

    os.remove(pathin)

    path = pathout + f"\\{os.listdir(pathout)[0]}\\docs\\static\\api"

    directory = os.fsencode(path)
    for file in os.listdir(directory):
        filepath = os.fspath(file)
        with open(directory + b"\\" + filepath, "r") as f:
            parse(json.load(f), prefix)

    shutil.rmtree(pathout)

loadrepository("https://github.com/lj-expand/lj-expand/archive/refs/heads/expansion.zip", "lje.")
loadrepository("https://github.com/lj-expand/lje-ffi/archive/refs/heads/main.zip", "ffi.")

outstring = (
              "--- This file was automatically generated by lje-util using the documentation inside of lje-util and lje-ffi\n"
            + "--- This can be updated by running lje-util/generate_annotations.py\n\n"
            + "--- LJE's namespace containing all functions and data related to it\n"
            + "lje = {} --- @diagnostic disable-line\n\n"
            + "--- LJE-FFI's namespace containing all functions and data related to it\n"
            + "ffi = {} --- @diagnostic disable-line\n\n"
            + "\n\n".join(namespaces)
            + "\n\n"
            + "\n\n".join(output)
            )
with open("\\".join(__file__.split("\\")[:-1]) + "\\modules\\annotations.lua", "w") as f:
    f.write(outstring)